# Generated by Django 2.2.10 on 2020-03-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule", name="any", field=models.BooleanField(default=True),
        ),
    ]
