# Generated by Django 2.2.10 on 2020-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_rule_any"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logicalcondition",
            name="operator",
            field=models.CharField(
                choices=[
                    ("gt", ">"),
                    ("gte", ">="),
                    ("lt", "<"),
                    ("lte", "=<"),
                    ("all", "all"),
                    ("any", "any"),
                ],
                max_length=10,
                verbose_name="Operator",
            ),
        ),
    ]
