# Generated by Django 2.2.10 on 2020-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0003_auto_20200329_1621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logicalcondition",
            name="operator",
            field=models.CharField(
                choices=[
                    ("gt", ">"),
                    ("gte", ">="),
                    ("lt", "<"),
                    ("lte", "=<"),
                    ("all", "all"),
                    ("any", "any"),
                    ("eq", "="),
                ],
                max_length=10,
                verbose_name="Operator",
            ),
        ),
    ]
