# Generated by Django 2.2.10 on 2020-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0004_auto_20200324_2345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logicalcondition",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("age", "Age"),
                    ("symptoms", "Symptoms"),
                    ("risk_factors", "Risk Factors"),
                ],
                max_length=20,
                verbose_name="Attribute",
            ),
        ),
    ]
