# Generated by Django 2.2.10 on 2020-03-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0005_auto_20200325_0009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logicalcondition",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("age", "Age"),
                    ("symptoms", "Symptoms"),
                    ("risk_factors", "Risk Factors"),
                    ("encounter_distance", "Encounter Distance"),
                    ("encounter_duration", "Encounter Duration"),
                ],
                max_length=20,
                verbose_name="Attribute",
            ),
        ),
        migrations.AlterField(
            model_name="logicalcondition",
            name="operator",
            field=models.CharField(
                choices=[
                    ("gt", ">"),
                    ("gte", ">="),
                    ("lt", "<"),
                    ("lte", "=<"),
                    ("IN", "in"),
                ],
                max_length=10,
                verbose_name="Operator",
            ),
        ),
    ]
