# Generated by Django 2.2.10 on 2020-03-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0002_auto_20200329_1450"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonToken",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Key",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to="tracking.Person",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "PersonToken",
                "verbose_name_plural": "PersonTokens",
                "abstract": False,
            },
        ),
    ]
