# Generated by Django 2.2.10 on 2020-03-25 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Desconhecido"),
                            ("S", "Suspeita de Corona Vírus"),
                            ("R", "Recuperado"),
                            ("C", "Corona Vírus Confirmado"),
                            ("N", "Negativado"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("beacon_id", models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="symptoms",
                        to="rules.LogicalCondition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_factors",
                        to="rules.LogicalCondition",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Risk Factors",},
        ),
        migrations.CreateModel(
            name="PersonSymptomReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptoms_reports",
                        to="tracking.Person",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="tracking.Symptom",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonStatusChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "previous",
                    models.CharField(
                        choices=[
                            ("D", "Desconhecido"),
                            ("S", "Suspeita de Corona Vírus"),
                            ("R", "Recuperado"),
                            ("C", "Corona Vírus Confirmado"),
                            ("N", "Negativado"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                (
                    "next",
                    models.CharField(
                        choices=[
                            ("D", "Desconhecido"),
                            ("S", "Suspeita de Corona Vírus"),
                            ("R", "Recuperado"),
                            ("C", "Corona Vírus Confirmado"),
                            ("N", "Negativado"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                (
                    "health_professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_status_changes",
                        to="tracking.Person",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Person Status Changes",},
        ),
        migrations.CreateModel(
            name="PersonRiskFactor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_factors",
                        to="tracking.Person",
                    ),
                ),
                (
                    "risk_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="tracking.RiskFactor",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Person Risk Factors",},
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("duration", models.PositiveIntegerField()),
                ("min_distance", models.FloatField()),
                (
                    "person_one",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_as_first_person",
                        to="tracking.Person",
                    ),
                ),
                (
                    "person_two",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_as_second_person",
                        to="tracking.Person",
                    ),
                ),
            ],
        ),
    ]
