# Generated by Django 2.2.10 on 2020-03-28 22:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonEncounters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_beacon_id", models.CharField(db_index=True, max_length=36)),
                (
                    "encountered_persons_beacons_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=36), size=None
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
