# Generated by Django 2.2.10 on 2020-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="sex",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("N", "Não declarar")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
