# Generated by Django 2.2.10 on 2020-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_auto_20200329_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="city",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="encounter",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
