# Generated by Django 2.2.10 on 2020-03-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_personencounters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personencounters",
            old_name="encountered_persons_beacons_ids",
            new_name="encountered_people_beacons_ids",
        ),
        migrations.AlterField(
            model_name="personriskfactor",
            name="risk_factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="tracking.RiskFactor",
            ),
        ),
        migrations.AlterField(
            model_name="personsymptomreport",
            name="symptom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="tracking.Symptom",
            ),
        ),
    ]
