# Generated by Django 2.2.10 on 2020-03-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_encounter'),
        ('tracking', '0005_riskfactor_rule'),
    ]

    operations = [
    ]
